touch src/domains/alarm-control-panel.extension.ts
touch src/domains/binary-sensor.extension.ts
touch src/domains/button.extension.ts
touch src/domains/camera.extension.ts
touch src/domains/climate.extension.ts
touch src/domains/cover.extension.ts
touch src/domains/date.extension.ts
touch src/domains/datetime.extension.ts
touch src/domains/fan.extension.ts
touch src/domains/humidifier.extension.ts
touch src/domains/image.extension.ts
touch src/domains/index.ts
touch src/domains/lawn-mower.extension.ts
touch src/domains/light.extension.ts
touch src/domains/lock.extension.ts
touch src/domains/media-player.ts
touch src/domains/notify.extension.ts
touch src/domains/number.extension.ts
touch src/domains/remote.extension.ts
touch src/domains/scene.extension.ts
touch src/domains/select.extension.ts
touch src/domains/sensor.extension.ts
touch src/domains/siren.extension.ts
touch src/domains/switch.extension.ts
touch src/domains/text.extension.ts
touch src/domains/time.extension.ts
touch src/domains/todo-list.extension.ts
touch src/domains/update.extension.ts
touch src/domains/vacuum.extension.ts
touch src/domains/valve.extension.ts
touch src/domains/water-heater.extension.ts
